version: '1.29.2'

services:
  postgres:
     container_name: postgres_db
     image: postgres
     ports:
        -5432:5432

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    ports:
      -5050:80

  mongodb:
    container_name: mongo_db
    image: mongo
    ports:
      -27017:27017
  
  mail:
    container_name: email
    image: maildev/maildev
    ports:
      -1080:1080
      -1025:1025

networks:
  microservices-net
  

volumes:
  postgres:
  pgadmin:
  mongodb: